### ISSUE TITLE
Release binary does not work in a Docker container

### ISSUE THREAD

**Issue by bep** [magefile/mage#69]
I may investigate this later, but thought I should post this in case someone else has any tips:

```bash
Resolving deltas: 100% (28797/28797), done.
Error: magefile.go:6:2: could not import bytes (cannot find package "bytes" in any of:
	/go/src/github.com/gohugoio/hugo/vendor/bytes (vendor tree)
	/Users/finchnat/src/github.com/golang/go/src/bytes (from $GOROOT)
	/go/src/bytes (from $GOPATH))
```

I use the Linux binary from the v1 release.

**Comment by natefinch** [comment]
that's so weird, why does it think it's using the goroot from my laptop?

**Comment by bep** [comment]
It works if I do `go get github.com/magefile/mage`. Fails with https://github.com/magefile/mage/releases/download/v1/mage_linux_amd64

I use the `golang:1.9.1` docker image as base. Can it be the Go version?

```
uname -a
Linux 908b889ddda8 4.4.86-boot2docker #1 SMP Tue Sep 5 23:59:54 UTC 2017 x86_64 GNU/Linux
```

**Comment by natefinch** [comment]
The binaries were built with go 1.9.0, though I can't imagine it matters. it's just running the go command with of.environs passed through.

**Comment by Xe** [comment]
I have the same issue with my [Alpine package](https://github.com/Xe/aports/blob/master/core/mage/APKBUILD) [here](https://gist.github.com/Xe/417bd57649a456ddfcfacda21148fdeb). I am considering fixing this by wrapping mage in a small shell script, IE:
```shell
#!/bin/sh

export $(go env)

exec /usr/share/mage/libexec/mage
```
```

**Comment by natefinch** [comment]
does it work on a Linux machine aside from docker?  I wonder if this is a problem with all the binaries.  I won't have time to test them until tonight.

**Comment by natefinch** [comment]
after some discussion on golang nuts, I have a fix, it'll be forthcoming, hopefully tonight. and I'll see about using goreleaser too.

**Comment by natefinch** [comment]
fixed with https://github.com/magefile/mage/pull/70 
See the new release: https://github.com/magefile/mage/releases/tag/v1.0.1

**Comment by bep** [comment]
This still doesn't work: 

```bash
Error: mage.go:5:9: could not import fmt (cannot find package "fmt" in any of:
	/Users/finchnat/src/github.com/golang/go/src/fmt (from $GOROOT)
	/go/src/fmt (from $GOPATH))
root@a7699ceb0bec:/go# mage -version
Mage Build Tool 1.0.1
Build Date: 2017-10-16T03:55:08Z
Commit: e66e3df1f2a53233ad48e5e874a0e532c65592dd
root@a7699ceb0bec:/go#
```

`mage.go` is a very simple build file and it, obviously, also fails for more complex scenarios:

```go
// +build mage

package main

import ("fmt")

func Build() {
    fmt.Println("hi")
}
```

**Comment by natefinch** [comment]
Ahh crap, I realize now that the test I ran did not actually test the bug..
I forgot to import something in my magefile.

Gah, this seems like a compiler bug.
